language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
before-script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - rails db:create
  - rails db:schema:load
script:
  - rails test
  - rails test:system