language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - npm install
before-script:
  - bundle install
  - yarn
  - rails db:create
  - rails db:schema:load
script:
  - rails test
  - rails test:system
os: windows # build only working on windows architectures for now -- cant figure out why